### ISSUE TITLE
discuss how to model data in Mongo

### ISSUE THREAD

**Issue by klaeufer** [sshilpika/metrics-dashboard-commit-density#4]
https://github.com/sshilpika/metrics-dashboard-commit-density/blob/master/src/main/scala/service/CommitDensityMetrics.scala#L68

We might want to have one document per file in the repo rather than one collection per file. Then we might be able to use indexing more effectively. This kind of tradeoff is discussed here:

http://stackoverflow.com/questions/15314769/mongodb-multiple-collections-or-one-big-collection-w-index

**Comment by sshilpika** [comment]
Does not apply any more.
