### ISSUE TITLE
proposed coding standards for complex logic involving different monads

### ISSUE THREAD

**Issue by klaeufer** [sshilpika/metrics-dashboard-commit-density#6]
I think part of the complexity comes from having a future around a collection. Perhaps certain coding standards can help manage this complexity and make the code more readable. Some ideas:
1. Follow the [Scala style guide](http://docs.scala-lang.org/style/method-invocation.html#higherorder_functions)'s recommendations for higher-order function invocation.
2. Use our own naming conventions consistently, e.g., use the suffix `F` to name futures.
3. Break up chains of transformations even more, e.g., replace
   
   ```
   val finalRes = collection.map(_.filter(!_.contains("system.indexes"))) flatMap
   ```
   
   with 
   
   ```
     val intermediateResF = collection map (_ filter (! _.contains("system.indexes")))
     val finalResF = intermediateResF flatMap ...
   ```
4. Keep the amount of nesting to a minimum, e.g., replace
   
   ```
   ... flatMap (p => /* long block */)
   ```
   
   with
   
   ```
     def descriptiveName(p: ...) = /* long block */
     ... flatMap descriptiveName
   ```

**Comment by sshilpika** [comment]
Moving this issue to ingestion service.
